server:
  port: 8890

spring:
  # DataSource Config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.162.134:3306/easywork?useSSL=false
    username: root
    password: Root
  #redis
  redis:
    database: 0
    host: 192.168.162.134
    port: 6379
    password: redis
    pool:
      jedis:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 1
    timeout: 1000
    cache:
      user:
        key: redis_user_
#mybatis
mybatis:
  mapper-locations: classpath:/com/gao/**/*Mapper.xml
  type-aliases-package: com.gao.entity
